openapi: 3.0.0

info: 
  title: Shopease
  description: The API collection for Shopease
  version: 1.0.0

servers: 
  - url: http://localhost:9000/api/v1
    description: Shopease Development Server
  - url: http://api.shopease.shubhampurwar.in/api/v1
    description: Shopease Production Server

tags: 
  - name: Authentication
    description: Authentication API
  - name: Users
    description: Users API
  - name: Addresses
    description: Addresses API
  - name: Cart
    description: Cart API
  - name: Wishlist
    description: Wishlist API
  - name: Products
    description: Products API
  - name: Categories
    description: Categories API
  - name: Brands
    description: Brands API
  - name: Coupons
    description: Coupons API
  - name: Orders
    description: Orders API
  - name: Reviews
    description: Reviews API
    
paths: 
  /auth/signup:
    post: 
      tags: 
        - Authentication
      description: Creates an account or restores a deleted one
      operationId: signup
      requestBody: 
        description: A JSON object containing signup information
        required: true
        content: 
          application/json:
            schema: 
              type: object
              properties: 
                firstname: 
                  type: string
                lastname:
                  type: string
                email:
                  type: string
                phone: 
                  type: string
                password: 
                  type: string
                confirmPassword: 
                  type: string
      responses: 
        '200': 
          description: Restored account
          content:
            application/json:
              schema: 
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/User'
        '201':
          description: Newly created account
          content: 
            application/json:
              schema: 
                type: object
                properties: 
                  success: 
                    type: boolean
                  message: 
                    type: string
                  data:
                    $ref: '#/components/schemas/User'
  /auth/login: 
    post:
      tags:
        - Authentication
      description: Allows users to login using their email address and password
      operationId: login
      requestBody:
        description: A JSON object containing login information
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password: 
                  type: string
      responses:
        '200': 
          description: Login success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'

  /auth/logout:
    post:
      tags:
        - Authentication
      description: Allows users to log out
      operationId: logout
      responses:
        '200':
          description: Logout success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
  
  /auth/password/forgot:
    post:
      tags:
        - Authentication
      description: Sends an email to the user with reset password link
      operationId: forgotPassword
      requestBody:
        description: A JSON object containing an email address
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
      responses:
        '200':
          description: Password reset email sent successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'

  /auth/password/reset/{token}:
    put:
      tags: 
        - Authentication
      description: Allows users to reset their account password
      operationId: resetPassword
      parameters:
        - in: path
          name: token
          required: true
          description: Reset password token
          schema:
            type: string
      requestBody:
        description: A JSON object containing new and confirmed passwords
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                confirmPassword:
                  type: string
      responses:
        '200':
          description: Password reset success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'

components:
  schemas:
    Success:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string

    User: 
      type: object
      properties: 
        id: 
          type: string
        firstname: 
          type: string
        lastname: 
          type: string
        fullname:
          type: string
        email:
          type: string
        phone: 
          type: string
        role:
          type: string
        avatar:
          type: object
          properties:
            url:
              type: string
            publicId:
              type: string
        cart:
          type: array
          items:
            type: object
            properties:
              product:
                type: string
              quantity:
                type: integer
        wishlist:
          type: array
          items:
            type: string
        resetPasswordToken:
          type: string
        resetPasswordExpiry:
          type: string
        isDeleted:
          type: boolean
        deletedBy:
          type: string
        roleLastUpdatedBy:
          type: string
        deletedAt:
          type: string
        roleUpdatedAt:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string

          